#!/usr/bin/env bash
set -uo pipefail

# Generated by `contextkit install-hooks --target codex`; do not edit by hand.
# Codex loads the generated context itself through `.contextkit.md`; this hook
# refreshes it and prints a notice only when the session needs one.

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
ROOT="$(cd "$ROOT" && pwd -P)"
cd "$ROOT"

export PATH="$ROOT/.contextkit/manager:$PATH"

exec contextkit session-start --host codex
